rwx-research/mint-cli

.mint/release.yml

We renamed `kv-outputs` and `kvOutputs` to `values` to be a little less duplicative in the `outputs` section.

KV Outputs -> Values

---

.mint/release.yml

`gh release` depends on the `.git` directory -- that's obvious in hindsight but I missed it in my last PR.

Include git-clone in tasks that use 'gh release'

---

.mint/continuous_integration.yml
cmd/mint/run.go

`--init-parameter` is pretty verbose and we use `init:` elsewhere (in the run definitions). This is a breaking change, but I'll update usage once merged and released.

Replace --init-parameter with --init for brevity and to match the run definition triggers

---

cmd/mint/run.go
internal/cli/config.go
internal/cli/service.go
internal/cli/service_test.go
internal/client/client.go
internal/client/config.go

Previously `mint abc def` would return
> Error: accepts at most 1 arg(s), received 2
Now this successfully sends up both `abc` and `def` as targeted tasks.
This depends on related Cloud and Mint PRs to be merged

Support targeting multiple task keys

---

internal/client/client.go
internal/client/client_suite_test.go
internal/client/client_test.go

Currently our endpoint looks like `<mint-host>/api/runs`.
With the move to cloud.rwx.com, it will look like `cloud.rwx.com/mint/api/runs`. To accommodate this, I need to conditionally modify the endpoint base path based on the host.
I kept it defaulting `MINT_HOST` to mint.rwx.com, but if you pass a custom `MINT_HOST` w/ cloud in it, it will perform the prefix.
I will replace these defaults with a cloud.rwx.com host and a /mint base path once cut over.
---
Please rip my go apart. It's been a minute.
Note run initiated using both mint hosts. Because cloud still has the old host as primary you can see it reports the run url using the soon to be deprecated host.

Add mint api base path

---

internal/client/client.go

We changed the response format on Cloud but forgot to make the change here. I've added putting some tests around this to my list of missing bigtest tests to make sure we don't break this again in the future.

Fixes parsing errors from Cloud

---

cmd/mint/debug.go
cmd/mint/require_access_token.go
cmd/mint/run.go

This addresses some discussion @TAGraves and I had around the help text/access token requirements.
```bash
$ ./mint run
Error: You're trying to use a command which requires authentication with RWX Cloud, but you do not have an access token configured.
To use this command, you can authenticate with RWX Cloud via the `mint login` command, or you can supply the `--access-token` option or `RWX_ACCESS_TOKEN` environment variable.
Once you do so, go ahead and run the command again.
$ ./mint debug 1
Error: You're trying to use a command which requires authentication with RWX Cloud, but you do not have an access token configured.
To use this command, you can authenticate with RWX Cloud via the `mint login` command, or you can supply the `--access-token` option or `RWX_ACCESS_TOKEN` environment …
```

Require authentication in mint run and mint debug

---

cmd/mint/login.go

I'd like to set `--open=false` for the playwright tests so they don't open when running them locally

Allow opting out of browser open

---

cmd/mint/run.go
internal/api/client.go
internal/api/client_test.go
internal/api/config.go
internal/api/task_definition.go
internal/cli/service.go

Updates the `InitiateRun` client function to send snake case and structured init params. It also updates it to accept snake case or camelcase responses from the endpoint so we can transition that to snake case as well.

Use snake case in the initiate run endpoint, send structured init params

---

cmd/mint/root.go
cmd/mint/vaults.go
internal/api/client.go
internal/api/client_test.go
internal/api/config.go
internal/cli/config.go
internal/cli/interfaces.go
internal/cli/service.go
internal/cli/service_test.go
internal/mocks/api.go

This adds a new command which can be used to set secrets programmatically.
The command is used like so:
```
mint vaults set-secrets --vault default ABC=123 DEF=xyz
```
Or, you can pass the secrets in via a file in the dotenv format:
```
mint vaults set-secrets --vault default --file secrets.txt
```

Adds mint vaults set-secrets

---

internal/cli/service.go
internal/errors/errors.go

We've previously returned a somewhat cryptic error message if the ssh session was closed by the agent. This is the case if a task or run is cancelled, for example.

Improve error message when debug session is cancelled

---

cmd/mint/run.go
internal/api/config.go
internal/cli/config.go
internal/cli/service.go

When initiating a run from the CLI, you'll now be able to specify a title which will be used when displaying the run in the Mint CLI.

Adds a flag to specify a title

---

.mint/bigtest.yml

This is required for bigtest to be able to run.

Configure a tool cache vault for bigtest

---

cmd/mint/run.go
internal/api/config.go
internal/cli/config.go
internal/cli/service.go
internal/cli/service_test.go
internal/fs/file_system.go
internal/fs/local.go
internal/mocks/file_system.go

With the upcoming release of Embedded Runs, we need to better define the behavior around `--dir` and `--file`.
Previously, these flags were mutually exclusive. You could provide:
- Nothing. In this case, we'd look in `.mint` in your working directory and try to run any task definitions at the top-level of that folder
- `--dir some-dir`. In this case, we'd look in that directory for run definitions and try to run them
- `--file some-file.yml`. In this case, we'd ignore any `.mint` directories and simply send the one task definition you specified
Moving forward, embedded runs need the context of a `.mint` dir to populate the run definitions that can be statically embedded (via `call: ${{ mint.run-dir }}/tasks.yml`). To facilitate this, the CLI needs to differentiate between the task …

Improve the behavior of --dir and --file

---

internal/accesstoken/file_backend.go
internal/accesstoken/file_backend_test.go

Editors often pad files with a trailing newline. When setting `~/.mint/accesstoken` manually, this was causing errors when usinng the token in http requests (a newline is not valid in the header)

Clean up whitespace surrounding the token in case it was manually set

---

.mint/release.yml

This change migrates the release process for the CLI over to use the new [parallelism](https://www.rwx.com/docs/mint/parallelism) feature. This reduces quite a bit of duplication we had in here and aligns it more closely to [Captain's release process](https://github.com/rwx-research/captain/blob/2fa181bfa387a8dae181183b7970ae9d30e5e66b/.github/workflows/release.yaml#L125-L186) which we still have running in GHA.

Use parallelism for the release process

---

cmd/mint/leaves.go

We've removed the requirement from the API for authentication to this endpoint.

Don't require authentication to list Mint leaves via API.

---

internal/api/client.go

We currently only print a server-provided error message on 400. This also adds it to 410

Print user-facing error message on 410 reponse when debugging

---

.mint/release.yml

When we switched this off of nix, we must have misunderstood what the `-compile` flag does. It builds a static binary _of mage_, not of your CLI.
For some reason I couldn't get `mage build` to work. It was trying to execute the version of mage for the platform we were trying to build for (e.g. the windows build was trying to execute mage.exe). This should have been fixed in https://github.com/magefile/mage/pull/202 but it seems like it wasn't. I decided to bypass mage altogether for the sake of expediency.
Tested with this release: https://github.com/rwx-research/mint-cli/releases/tag/untagged-ce7a12e2f5930bf6d86a

Fixes the release build

---

cmd/mint/lint.go
cmd/mint/main.go
cmd/mint/root.go
cmd/mint/run.go
internal/api/client.go
internal/api/config.go
internal/api/nullable.go
internal/api/task_definition.go
internal/cli/config.go
internal/cli/interfaces.go
internal/cli/service.go
internal/cli/service_test.go
internal/fs/file.go
internal/memoryfs/file_system.go
internal/mocks/api.go
internal/mocks/file_system.go

Add `mint lint` as a hidden/beta feature. When this command is stable we will include it in the list of available commands in `mint help`.
Output options include `oneline`:
```text
error   .mint/continuous_integration.yml:13:5 - Unexpected property `bad`
error   .mint/continuous_integration.yml:27:5 - Unexpected property `wat`
error   .mint/run-bad.yml:2:5 - Expected a task with a `run` key, a leaf with a `call` key, or an embedded run with a `call` key
```
`multiline`:
```text
.mint/continuous_integration.yml:13:5  [error]
Unexpected property `bad`
Expected one of the following keys: `id`, `if`, `capacity`, `on-overflow`
.mint/continuous_integration.yml:27:5  [error]
Unexpected property `wat`
Expected one of the following keys: `key`, `use`, `after`, `if`, `filter`, `cache`, `call`, …
```

Add `mint lint` command.

---

internal/cli/service.go
internal/cli/service_test.go

Includes detail on the number of files checked by `mint lint` when multiline output is used.
```
.mint/release.yml:110:5  [error]
Unexpected property `enX`
Expected one of the following keys: `agent`, `key`, `use`, `after`, `if`, `filter`, `cache`, `run`, `background-processes`, `outputs`, `env`, `env-config`, `timeout-minutes`, `tool-cache`, `parallel`, `docker`
Checked 4 files and found 1 problem.
```

Include final counts in multiline mint-lint output.

---

internal/api/client.go
internal/api/config.go
internal/cli/service.go
internal/cli/service_test.go
internal/messages/messages.go
internal/messages/messages_suite_test.go
internal/messages/messages_test.go

This makes the CLI aware of stack traces and frames, and it now constructs errors and warnings using those when it can. While I was in here, I made the multiline lint format match the same format as what is printed for `mint run`. The single line format remains unchanged. This also is fully backwards compatible.

Adds support for new user message format for runs and linting

---

internal/api/client_test.go
internal/api/config.go
internal/api/mint_directory_entry.go
internal/cli/service.go
internal/cli/service_test.go

With this change, we'll send the entire structure of the `.mint` directory to cloud along with all file contents. We _won't_ do anything other than track the path/type/permissions for things that are not files (no following symlinks or trying to replicate devices/sockets/etc)

Recursively send the entire mint directory contents, not just the first level of yaml

---

internal/cli/service.go
internal/cli/service_test.go

When `--dir` points to a file, we should return an error

Do not grab mint directory entries when it is not a directory

---

.mint/release.yml

Add a statically-linked musl version for mint-cli releases.

---

cmd/mint/leaves.go
cmd/mint/lint.go
cmd/mint/login.go
cmd/mint/root.go
cmd/mint/vaults.go
cmd/mint/whoami.go
go.mod
go.sum
internal/api/client.go
internal/api/client_test.go
internal/api/debug_connection_info.go
internal/cli/config.go
internal/cli/service.go
internal/cli/service_test.go
internal/messages/messages.go
internal/messages/messages_test.go
internal/versions/interceptor.go
internal/versions/versions.go

When the Mint CLI connects to Cloud, capture the latest version (if available). Compare this to the currently-running version and outputs a message to stderr:
```
========================================
A new version of Mint is available!
You are currently on version 1.0.2
The latest version is 1.3.2
========================================
```
If we believe you installed the CLI through Homebrew, we'll include instructions for upgrading:
```
========================================
A new version of Mint is available!
You are currently on version 1.0.2
The latest version is 1.3.2
You can update to the latest version with:
brew upgrade rwx-research/tap/mint
========================================
```
These messages are output before any command output (and only to stderr). Output can be …

Output message when not running the latest CLI version.

---

.tool-versions
cmd/mint/root.go
cmd/mint/run.go
internal/api/client.go
internal/api/debug_connection_info.go
internal/cli/service.go
internal/cli/service_test.go
internal/errors/errors.go

This will automatically connect to a debug session in case a breakpoint is hit.
**Note the following  breaking change:** We previously already had `--debug` flag defined, which made log output more verbose. This flag has been renamed to `--verbose`. Luckily, the flag was previously hidden (i.e. it was not documented in the help text, nor our documentation), so I feel confident that we can release this feature without bumping the major version number.

Add `--debug` flag to run command.

---

internal/cli/service.go
internal/cli/service_test.go

When initiating a CLI run via `mint run`, the target file is checked for a `base` configuration.
If the `base` is missing (or incomplete), automatically inject the missing configuration and save the run definition file. When this happens, a warning is output.
If `base` is already configured, the file is not changed and no server-side resolution is requested.
This message will be output to stderr ahead of the "run is watchable":
> Configured "../mint-defs/task.yml" to run on ubuntu 24.04
>
> Run is watchable at https://cloud.rwx.com/mint/rwx/runs/48e65c10216c40b187426479505f096c

On `mint run`, add a `base` configuration if missing

---

cmd/mint/leaves.go
cmd/mint/resolve.go
cmd/mint/root.go
cmd/mint/update.go
internal/cli/config.go
internal/cli/service.go
internal/cli/service_test.go

This allows targeting a specific file (which may or may not be in the `.mint` directory).
It also adds the new `mint update leaves` command to deprecate the `mint leaves update` command.

Add file targeting for `resolve base`, `resolve leaves`, and the new `update leaves` commands.

---

cmd/mint/dispatch.go
cmd/mint/leaves.go
cmd/mint/resolve.go
cmd/mint/root.go
cmd/mint/run.go
cmd/mint/update.go
internal/api/client.go
internal/api/mint_directory_entry.go
internal/cli/config.go
internal/cli/files.go
internal/cli/service.go
internal/cli/service_test.go
internal/cli/yaml.go
internal/cli/yaml_test.go
internal/versions/versions.go

* Add a `mint update base` command and include it in `mint update`
* Add a `mint resolve leaves` command and include it in `mint resolve`
* Use YAML parsing to make changes to run definitions, not string replacement
* Consolidate file-handling logic in `internal/cli/files.go`
* Clean up duplication

Add `mint update base` and refactor YAML file handling.

---

internal/cli/service.go
internal/cli/service_test.go

This fixes a scenario where running `mint update leaves` would not also resolve leaves that had no version, except when `--allow-major-version-change` was also selected.

Resolve leaves when updating leaves.

---

internal/cli/service.go
internal/cli/service_test.go
internal/cli/yaml.go

Fixes a crash when snippets files were present in the mint directory or specifically targeted.

Handle updating leaves in snippet files.
